/**
 * backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Project from './Project';

/**
 * The ProjectList model module.
 * @module model/ProjectList
 * @version 1.0
 */
class ProjectList {
    /**
     * Constructs a new <code>ProjectList</code>.
     * @alias module:model/ProjectList
     */
    constructor() { 
        
        ProjectList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProjectList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectList} obj Optional instance to populate.
     * @return {module:model/ProjectList} The populated <code>ProjectList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectList();

            if (data.hasOwnProperty('projects')) {
                obj['projects'] = ApiClient.convertToType(data['projects'], [Project]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProjectList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProjectList</code>.
     */
    static validateJSON(data) {
        if (data['projects']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['projects'])) {
                throw new Error("Expected the field `projects` to be an array in the JSON data but got " + data['projects']);
            }
            // validate the optional field `projects` (array)
            for (const item of data['projects']) {
                Project.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Project>} projects
 */
ProjectList.prototype['projects'] = undefined;






export default ProjectList;

