/**
 * backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateProjectRequest from './model/CreateProjectRequest';
import CreateTaskRequest from './model/CreateTaskRequest';
import IdResponse from './model/IdResponse';
import Project from './model/Project';
import ProjectList from './model/ProjectList';
import Task from './model/Task';
import ProjectsApi from './api/ProjectsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Backend = require('index'); // See note below*.
* var xxxSvc = new Backend.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Backend.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Backend.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Backend.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateProjectRequest model constructor.
     * @property {module:model/CreateProjectRequest}
     */
    CreateProjectRequest,

    /**
     * The CreateTaskRequest model constructor.
     * @property {module:model/CreateTaskRequest}
     */
    CreateTaskRequest,

    /**
     * The IdResponse model constructor.
     * @property {module:model/IdResponse}
     */
    IdResponse,

    /**
     * The Project model constructor.
     * @property {module:model/Project}
     */
    Project,

    /**
     * The ProjectList model constructor.
     * @property {module:model/ProjectList}
     */
    ProjectList,

    /**
     * The Task model constructor.
     * @property {module:model/Task}
     */
    Task,

    /**
    * The ProjectsApi service constructor.
    * @property {module:api/ProjectsApi}
    */
    ProjectsApi
};
